aarch64: true
appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c200fd287b5930700bda079
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: gmSmWYqFgXS3ctH8l7f46TEBz9XwwJF7lIMwIE+LQEWZA7xaosRO2ZLCfN/CpPxzIN/IfztTNPT0LOXgNLu5Yu8moYHgFLrX/P13Eq480OuTexHgyOY2/gbbTYcpywPHTjJXy2IDbKM5XWfvWNQwWqyfEigLA3zouTjlx+bHUwgAQa7F5DOR9Ypod/VWvylh+7nh1eVbqDbzTmqmqMC/El3Cy4gtt5NWdOuqx6hERVuWJ3YQCFZFPAvUHKXNasDIpIDRGMwP/pWrwHZhWXK+RP/VPgFmO0wxXAz23VKr43RZ06bsP9KecwuH2PSXGkfADc83HUZmc5qlbJApFsAheRhYtrdxQ9aFzww6JQ1DFGtC/Q7+HexKPFTQ6c/kYsSb05DMaN8eXaicAkteB32cPI1qMKe44/QUWvHs+NFu5DHwkKkIYzKbLcWyVQqumrg4fvyhBVuaJsavdAeRgwumB+vJhJwWaZj14KvQte9BBQyjLVeM0xvEOAX/vxCTmXsROY8nX2GN+TaErBikLRH8x6ktXGTaWxu3X0YmDcAaKPmQ+aBJJ1ztiACkeIsqp5wm4wSw8MhVldttjQhhxJpGPKXIGX3Ty5hslgS8OLYpVqyL2Vl3F/A53Kx2RznpKTj0b8ZlWlXTGdhPPanD7oCqWpFLPAWbwIpKIWnCpOfI5Z4=}
